- name: "Docker: install requirements"
  apt:
    name: "{{ item }}"
    update_cache: true
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common

- name: "Docker: add GPG key"
  apt_key:
    url: https://download.docker.com/linux/debian/gpg

- name: "Docker: add repository"
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian stretch stable"

- name: "Docker: install Docker"
  apt:
    name: docker-ce
    update_cache: true

- name: "Docker: install Compose"
  get_url:
    url: https://github.com/docker/compose/releases/download/1.23.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0755
