version: 2.1

jobs:
  deploy:
    docker:
      - image: willhallonline/ansible:2.7-alpine
    steps:
      - checkout
      - run:
          name: Deploy
          command: ./run.sh deploy

  update-filharmonic:
    docker:
      - image: willhallonline/ansible:2.7-alpine
    steps:
      - checkout
      - run:
          name: "Update Fil'Harmonic"
          command: ./run.sh update-filharmonic

workflows:
  deploy:
    jobs:
      - deploy:
          requires: []

  update-filharmonic:
    triggers:
      - schedule:
          cron: "0 4 * * *" # Daily at 04:00
          filters:
            branches:
              only:
                - master
    jobs:
      - update-filharmonic:
          requires: []
