version: 2

jobs:
  deploy:
    docker:
      - image: totakoko/compose-deploy
    steps:
      - checkout
      - run:
          command: compose-deploy deploy
          environment:
            MODULES_ROOT: /root/project

  update-filharmonic:
    docker:
      - image: totakoko/compose-deploy
    steps:
      - checkout
      - run:
          name: "Update Fil'Harmonic"
          command: compose-deploy update-module filharmonic

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          requires: []
          filters:
            branches:
              only:
                - master

  update-filharmonic:
    triggers:
      - schedule:
          cron: "0 4 * * *" # Daily at 04:00
          filters:
            branches:
              only:
                - master
    jobs:
      - update-filharmonic:
          requires: []
