version: '3'

services:
  dns:
    image: coredns/coredns:1.3.1
    restart: unless-stopped
    ports:
      - "53:53"
      - "53:53/udp"
    volumes:
      - ./Corefile/:/Corefile:ro
      - ./zones/:/zones/:ro
