version: '3.5'

services:
  ui:
    image: betagouv/filharmonic-ui:latest
    restart: unless-stopped
    environment:
      - SENTRY_URL=https://b88000f087974028a3be1a5000c109e4@sentry.io/1364322
    networks:
      - web
      - filharmonic
    labels:
      - "traefik.enable=true"
      - "traefik.port=5000"
      - "traefik.frontend.rule=Host:filharmonic.beta.gouv.fr"
      - "traefik.docker.network=web"

  api:
    image: betagouv/filharmonic-api:latest
    restart: unless-stopped
    depends_on:
      - postgresql
    environment:
      - "FILHARMONIC_DATABASE_HOST=postgresql"
      - "FILHARMONIC_DATABASE_PASSWORD=filharmonic_password"
    networks:
      - web
      - filharmonic
    labels:
      - "traefik.enable=true"
      - "traefik.port=5000"
      - "traefik.frontend.rule=Host:filharmonic.beta.gouv.fr; PathPrefixStrip:/api"
      - "traefik.docker.network=web"

  postgresql:
    image: postgres:11.1-alpine
    restart: unless-stopped
    environment:
      - "POSTGRES_USER=filharmonic"
      - "POSTGRES_PASSWORD=filharmonic_password"
      - "POSTGRES_DB=filharmonic"
    volumes:
      - /srv/data/filharmonic/postgresql:/var/lib/postgresql/data
    networks:
      - filharmonic

  cas:
    image: tristanrobert/cas:latest
    restart: unless-stopped
    networks:
      - web
      - filharmonic
    labels:
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:cas.filharmonic.beta.gouv.fr"
      - "traefik.docker.network=web"

networks:
  filharmonic:
  web:
    external: true
